/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converters;

import java.awt.event.KeyEvent;

/**
 *
 * @author cstuser
 */
public class WeightConverter extends javax.swing.JFrame {

    /**
     * Creates new form WeightConverter
     */
    public WeightConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeGroup = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        kgLabel = new javax.swing.JLabel();
        equalLabel = new javax.swing.JLabel();
        lbLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        kgTF = new javax.swing.JTextField();
        lbTF = new javax.swing.JTextField();
        kg2lbRB = new javax.swing.JRadioButton();
        lb2kgRB = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weight Converter");

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setText("Weight Converter");

        kgLabel.setText("KG");

        equalLabel.setText("=");

        lbLabel.setText("LB");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        kgTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kgTFKeyReleased(evt);
            }
        });

        lbTF.setEditable(false);
        lbTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbTFKeyReleased(evt);
            }
        });

        modeGroup.add(kg2lbRB);
        kg2lbRB.setSelected(true);
        kg2lbRB.setText("KG to LB");
        kg2lbRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kg2lbRBActionPerformed(evt);
            }
        });

        modeGroup.add(lb2kgRB);
        lb2kgRB.setText("LB to KG");
        lb2kgRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb2kgRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(kgTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kgLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb2kgRB)
                                    .addComponent(kg2lbRB))
                                .addGap(81, 81, 81)
                                .addComponent(submitButton)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kgLabel)
                    .addComponent(equalLabel)
                    .addComponent(lbLabel)
                    .addComponent(kgTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kg2lbRB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb2kgRB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (kg2lbRB.isSelected())
            convertToLb();
        else
            convertToKg();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void kgTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kgTFKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            convertToLb();
    }//GEN-LAST:event_kgTFKeyReleased

    private void lb2kgRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb2kgRBActionPerformed
        kgTF.setEditable(false);
        lbTF.setEditable(true);
        kgTF.setText("");
        lbTF.setText("");
    }//GEN-LAST:event_lb2kgRBActionPerformed

    private void kg2lbRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kg2lbRBActionPerformed
        kgTF.setEditable(true);
        lbTF.setEditable(false);
        kgTF.setText("");
        lbTF.setText("");
    }//GEN-LAST:event_kg2lbRBActionPerformed

    private void lbTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbTFKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            convertToKg();
    }//GEN-LAST:event_lbTFKeyReleased

    private void convertToLb() {
        if (kgTF.getText().isEmpty())
            return;
        
        double source = Double.parseDouble(kgTF.getText());
        double result = source * 2.2;
        lbTF.setText(String.format("%.2f", result));
    }
    
    private void convertToKg() {
        if (lbTF.getText().isEmpty())
            return;
        
        double source = Double.parseDouble(lbTF.getText());
        double result = source / 2.2;
        kgTF.setText(String.format("%.2f", result));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeightConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeightConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeightConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeightConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeightConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel equalLabel;
    private javax.swing.JRadioButton kg2lbRB;
    private javax.swing.JLabel kgLabel;
    private javax.swing.JTextField kgTF;
    private javax.swing.JRadioButton lb2kgRB;
    private javax.swing.JLabel lbLabel;
    private javax.swing.JTextField lbTF;
    private javax.swing.ButtonGroup modeGroup;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
