/*
 * The MIT License
 *
 * Copyright 2021 Yi Wang.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package convertor;

import java.awt.event.KeyEvent;

/**
 *
 * @author Yi Wang
 */
public class WeightConvertor extends javax.swing.JFrame {

    private Menu menu;  // -> pointting at the menu page

    /**
     * Creates new form WeightConvertor
     */
    public WeightConvertor(Menu menu) {
        this.menu = menu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeBG = new javax.swing.ButtonGroup();
        titleL = new javax.swing.JLabel();
        inputUnitL = new javax.swing.JLabel();
        inputTF = new javax.swing.JTextField();
        equalL = new javax.swing.JLabel();
        outputL = new javax.swing.JLabel();
        outputUnitL = new javax.swing.JLabel();
        submitB = new javax.swing.JButton();
        kg2LbRB = new javax.swing.JRadioButton();
        lb2KgRB = new javax.swing.JRadioButton();
        inputSL = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("weight converter");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        titleL.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        titleL.setText("Weight Converter");

        inputUnitL.setText("kg");

        inputTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputTFKeyReleased(evt);
            }
        });

        equalL.setText("=");

        outputUnitL.setText("lb");

        submitB.setText("Submit");
        submitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBActionPerformed(evt);
            }
        });

        modeBG.add(kg2LbRB);
        kg2LbRB.setSelected(true);
        kg2LbRB.setText("kg to lb");
        kg2LbRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kg2LbRBActionPerformed(evt);
            }
        });

        modeBG.add(lb2KgRB);
        lb2KgRB.setText("lb to kg");
        lb2KgRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb2KgRBActionPerformed(evt);
            }
        });

        inputSL.setMajorTickSpacing(25);
        inputSL.setMinorTickSpacing(5);
        inputSL.setPaintLabels(true);
        inputSL.setPaintTicks(true);
        inputSL.setToolTipText("");
        inputSL.setValue(0);
        inputSL.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                inputSLStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(titleL, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputTF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputUnitL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(equalL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputL, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputUnitL))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kg2LbRB)
                                    .addComponent(lb2KgRB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(submitB)
                                        .addGap(55, 55, 55))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(inputSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titleL)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputUnitL)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputTF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(equalL)
                        .addComponent(inputUnitL)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kg2LbRB)
                    .addComponent(inputSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb2KgRB)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitB)
                        .addGap(28, 28, 28))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the submit event, do the conversion
     *
     * @param evt the action
     */
    private void submitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBActionPerformed
        convertWeight();
    }//GEN-LAST:event_submitBActionPerformed

    /**
     * Reads the user input, and convert the weight, then set the result in the
     * output label
     */
    public void convertWeight() {
        String result = "";
        try {
            // read from the textfield
            double input = Double.parseDouble(inputTF.getText());

            // conversion
            if (kg2LbRB.isSelected())
                result = String.format("%.2f", kgToLb(input));
            else
                result = String.format("%.2f", lbToKg(input));

            // write to the result label
            outputL.setText(result);
        } catch (Exception e) {

        }
    }

    /**
     * sets the input unit as lb and the output unit as kg
     *
     * @param evt the event
     */
    private void lb2KgRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb2KgRBActionPerformed
        inputUnitL.setText("lb");
        outputUnitL.setText("kg");
        outputL.setText("");
    }//GEN-LAST:event_lb2KgRBActionPerformed

    /**
     * sets the input unit as kg and the output unit as lb
     *
     * @param evt the event
     */
    private void kg2LbRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kg2LbRBActionPerformed
        inputUnitL.setText("kg");
        outputUnitL.setText("lb");
        outputL.setText("");
    }//GEN-LAST:event_kg2LbRBActionPerformed

    /**
     * converts the values with enter key
     *
     * @param evt the event
     */
    private void inputTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTFKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            convertWeight();
    }//GEN-LAST:event_inputTFKeyReleased

    /**
     * Set the menu frame visible
     *
     * @param evt the closing event
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * update the input textfield when the slider value gets changed
     *
     * @param evt the slider statechanged event
     */
    private void inputSLStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_inputSLStateChanged
        inputTF.setText(inputSL.getValue() + "");
    }//GEN-LAST:event_inputSLStateChanged

    /**
     * converts kg to lb
     *
     * @param kg the input kg
     * @return the converted lb
     */
    public double kgToLb(double kg) {
        final double kg2lbRatio = 2.2;
        return kg * kg2lbRatio;
    }

    /**
     * converts lb to kg
     *
     * @param lb the input lb
     * @return the converted kg
     */
    public double lbToKg(double lb) {
        final double lb2kgRatio = 0.4545;
        return lb * lb2kgRatio;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel equalL;
    private javax.swing.JSlider inputSL;
    private javax.swing.JTextField inputTF;
    private javax.swing.JLabel inputUnitL;
    private javax.swing.JRadioButton kg2LbRB;
    private javax.swing.JRadioButton lb2KgRB;
    private javax.swing.ButtonGroup modeBG;
    private javax.swing.JLabel outputL;
    private javax.swing.JLabel outputUnitL;
    private javax.swing.JButton submitB;
    private javax.swing.JLabel titleL;
    // End of variables declaration//GEN-END:variables
}
