/*
 * The MIT License
 *
 * Copyright 2021 Yi Wang.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package simpleschoolsystem;

/**
 *
 * @author Yi Wang
 */
public class homeFrame extends javax.swing.JFrame {

    private User user;      // store the infor of the user that login

    /**
     * Creates new form homeFrame
     */
    public homeFrame(User user) {
        initComponents();
        this.user = user;
        welcomeL.setText(String.format("welcome, %s", user.getUserName()));
        gradeP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeL = new javax.swing.JLabel();
        displayB = new javax.swing.JButton();
        gradeP = new javax.swing.JPanel();
        grade1L = new javax.swing.JLabel();
        grade2L = new javax.swing.JLabel();
        grade3L = new javax.swing.JLabel();
        grade4L = new javax.swing.JLabel();
        grade5L = new javax.swing.JLabel();
        gradeFinalL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeL.setText("welcome, ");

        displayB.setText("Display Grades");
        displayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBActionPerformed(evt);
            }
        });

        gradeP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        grade1L.setText("grade1");

        grade2L.setText("grade2");

        grade3L.setText("grade3");

        grade4L.setText("grade4");

        grade5L.setText("grade5");

        gradeFinalL.setText("final grade");

        javax.swing.GroupLayout gradePLayout = new javax.swing.GroupLayout(gradeP);
        gradeP.setLayout(gradePLayout);
        gradePLayout.setHorizontalGroup(
            gradePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(grade1L)
                .addGap(18, 18, 18)
                .addComponent(grade2L)
                .addGap(18, 18, 18)
                .addComponent(grade3L)
                .addGap(18, 18, 18)
                .addComponent(grade4L)
                .addGap(18, 18, 18)
                .addComponent(grade5L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gradeFinalL)
                .addGap(27, 27, 27))
        );
        gradePLayout.setVerticalGroup(
            gradePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(gradePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grade1L)
                    .addComponent(grade2L)
                    .addComponent(grade3L)
                    .addComponent(grade4L)
                    .addComponent(grade5L)
                    .addComponent(gradeFinalL))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(welcomeL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gradeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 380, Short.MAX_VALUE)
                        .addComponent(displayB)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(welcomeL)
                .addGap(18, 18, 18)
                .addComponent(gradeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(displayB)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBActionPerformed
        if (user instanceof Student) {
            double[] grades;
            grades = ((Student) user).getGrades();
            grades = new double[]{78, 92, 99, 69, 88};
            grade1L.setText("grade1: " + grades[0]);
            grade2L.setText("grade2: " + grades[1]);
            grade3L.setText("grade3: " + grades[2]);
            grade4L.setText("grade4: " + grades[3]);
            grade5L.setText("grade5: " + grades[4]);

            gradeFinalL.setText(calcAvgGrade(grades) + "");
            gradeP.setVisible(true);
        }
//        else
//            ((Teacher) user)
    }//GEN-LAST:event_displayBActionPerformed

    /**
     * calculates the average of the grades
     *
     * @param grades the input grades
     * @return the average of the grades
     */
    public double calcAvgGrade(double[] grades) {
        double avg = 0;
        for (double grade : grades)
            avg += grade;

        return avg / grades.length;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displayB;
    private javax.swing.JLabel grade1L;
    private javax.swing.JLabel grade2L;
    private javax.swing.JLabel grade3L;
    private javax.swing.JLabel grade4L;
    private javax.swing.JLabel grade5L;
    private javax.swing.JLabel gradeFinalL;
    private javax.swing.JPanel gradeP;
    private javax.swing.JLabel welcomeL;
    // End of variables declaration//GEN-END:variables
}
