/*
 * The MIT License
 *
 * Copyright 2021 Yi Wang.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package simpleschoolsystem;

import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author Yi Wang
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();

        signUpP.setVisible(false);   // hide the signUp panel
        ImageIcon titleImg1 = new ImageIcon("imgs\\user.png");   // create the img object
        ImageIcon titleImg2 = new ImageIcon("imgs\\user2.png");   // create the img object
        ImageIcon titleImg3 = new ImageIcon("imgs\\user3.png");   // create the img object
        ImageIcon titleImg4 = new ImageIcon("imgs\\user4.png");   // create the img object

        ImageIcon[] iis = {titleImg1, titleImg2, titleImg3, titleImg4};
        imgL.setIcon(iis[new Random().nextInt(iis.length)]);         // add the image to the image label

        SchoolSystem.initData();     // initialize the users

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userL = new javax.swing.JLabel();
        passwordL = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JTextField();
        loginB = new javax.swing.JButton();
        singUpB = new javax.swing.JButton();
        titleL = new javax.swing.JLabel();
        imgL = new javax.swing.JLabel();
        signUpP = new javax.swing.JPanel();
        userNameL = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        passwordSignUpL = new javax.swing.JLabel();
        passwordSignUpTF = new javax.swing.JTextField();
        fnameL = new javax.swing.JLabel();
        fnameTF = new javax.swing.JTextField();
        lnameL = new javax.swing.JLabel();
        lnameTF = new javax.swing.JTextField();
        submitB = new javax.swing.JButton();
        signUpMessageL = new javax.swing.JLabel();
        loginMessageL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userL.setText("user:");

        passwordL.setText("password:");

        loginB.setText("Login");
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });

        singUpB.setText("Sign Up");
        singUpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singUpBActionPerformed(evt);
            }
        });

        titleL.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        titleL.setText("Simple School System");

        imgL.setToolTipText("");

        signUpP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        userNameL.setText("user name:");

        passwordSignUpL.setText("password:");

        fnameL.setText("first name:");

        lnameL.setText("last name:");

        submitB.setText("Submit");
        submitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBActionPerformed(evt);
            }
        });

        signUpMessageL.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout signUpPLayout = new javax.swing.GroupLayout(signUpP);
        signUpP.setLayout(signUpPLayout);
        signUpPLayout.setHorizontalGroup(
            signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPLayout.createSequentialGroup()
                        .addComponent(signUpMessageL, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(submitB)
                        .addGap(25, 25, 25))
                    .addGroup(signUpPLayout.createSequentialGroup()
                        .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(signUpPLayout.createSequentialGroup()
                                .addComponent(lnameL)
                                .addGap(31, 31, 31)
                                .addComponent(lnameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .addGroup(signUpPLayout.createSequentialGroup()
                                .addComponent(fnameL)
                                .addGap(31, 31, 31)
                                .addComponent(fnameTF))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, signUpPLayout.createSequentialGroup()
                                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordSignUpL)
                                    .addComponent(userNameL))
                                .addGap(26, 26, 26)
                                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNameTF)
                                    .addComponent(passwordSignUpTF))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        signUpPLayout.setVerticalGroup(
            signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameL)
                    .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordSignUpL)
                    .addComponent(passwordSignUpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameL)
                    .addComponent(fnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameL)
                    .addComponent(lnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitB))
                    .addGroup(signUpPLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(signUpMessageL, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        loginMessageL.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(loginMessageL, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userL)
                                .addGap(42, 42, 42)
                                .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(titleL))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(singUpB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loginB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(imgL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(signUpP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleL)
                    .addComponent(imgL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userL)
                    .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(singUpB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordL)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginMessageL, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Set the sign up panel visible
     *
     * @param evt the button event
     */
    private void singUpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singUpBActionPerformed
        signUpP.setVisible(true);

        // focus on the user name textfield in the sign up pannel
        userNameTF.requestFocus();
    }//GEN-LAST:event_singUpBActionPerformed

    private void submitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBActionPerformed
        String userName = userNameTF.getText();
        String password = passwordSignUpTF.getText();
        String fname = fnameTF.getText();
        String lname = lnameTF.getText();

        User user;

        // if the userName starts with s, then it is a student
        // if the userName starts with t, then it is a teacher
        if (userName.charAt(0) == 's')
            user = new Student(userName, password, fname, lname);
//        else if (userName.charAt(0) == 't')
//            user = new Teacher(userName, password, fname, lname);
        else {
            signUpMessageL.setForeground(Color.RED);
            signUpMessageL.setText("The syntax of the username is incorrect.");
            return;
        }

        if (SchoolSystem.users.contains(user)) {
            // print an error message
            signUpMessageL.setForeground(Color.RED);
            signUpMessageL.setText("The user name is used, please change another one");
        } else {
            SchoolSystem.users.add(user);
            SchoolSystem.serializeData("users.ser", SchoolSystem.users);
            signUpMessageL.setForeground(Color.GREEN);
            signUpMessageL.setText("New user generated successfully");
        }
    }//GEN-LAST:event_submitBActionPerformed

    /**
     * checks for the login
     *
     * @param evt the login button event
     */
    private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed
        String inputUserName = userTF.getText();
        String password = passwordTF.getText();

        for (User existUser : SchoolSystem.users)
            if (existUser.getUserName().equals(inputUserName)
                    && existUser.getPassword().equals(password)) {
                // valid, jump to the new frame which contains the user's infor
                new homeFrame(existUser).setVisible(true);
                this.setVisible(false);
                return;
            }

        loginMessageL.setText("Your account or password is not correct");
    }//GEN-LAST:event_loginBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fnameL;
    private javax.swing.JTextField fnameTF;
    private javax.swing.JLabel imgL;
    private javax.swing.JLabel lnameL;
    private javax.swing.JTextField lnameTF;
    private javax.swing.JButton loginB;
    private javax.swing.JLabel loginMessageL;
    private javax.swing.JLabel passwordL;
    private javax.swing.JLabel passwordSignUpL;
    private javax.swing.JTextField passwordSignUpTF;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JLabel signUpMessageL;
    private javax.swing.JPanel signUpP;
    private javax.swing.JButton singUpB;
    private javax.swing.JButton submitB;
    private javax.swing.JLabel titleL;
    private javax.swing.JLabel userL;
    private javax.swing.JLabel userNameL;
    private javax.swing.JTextField userNameTF;
    private javax.swing.JTextField userTF;
    // End of variables declaration//GEN-END:variables
}
